models:
    build:  ./
    external_links:
      -  mysql:db
    volumes:
      - ../cs4501/app:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory /app/webapp  --reload-on-changes /app/webapp/webapp/wsgi.py"